import Foundation

/// Rough, on-device speaker diarization: recognizing *that* a recording contains
/// different voices and attributing turns to them, without identifying who they
/// are. Apple's on-device Speech stack provides no diarization, so this derives
/// it from the source audio: speaker-sized windows are embedded by an
/// `OnbiiSpeakerEmbedder`, the embeddings are clustered by voice similarity, and
/// each transcript word inherits the speaker label of the window it falls in.
///
/// Labels are opaque and per-object (`S1`, `S2`, …). They deliberately carry no
/// cross-object or personal meaning; mapping them to named people or reusable
/// voice signatures is a later, separately provenanced step. This is derived
/// data — it never alters the preserved source, and it can be regenerated by a
/// better model later.

// MARK: - Embedder boundary

/// Produces a fixed-length voice embedding for a time window of one audio track.
/// The Core ML implementation lives behind this boundary so the clustering and
/// assignment logic stays testable without a model, and so the embedding model
/// can be replaced.
public protocol OnbiiSpeakerEmbedder: Sendable {
    /// A voice embedding for the audio in `[start, end)` seconds, or `nil` when
    /// the window cannot be embedded (too short, silent, or unreadable). The
    /// vector need not be normalized; clustering normalizes internally.
    func embedding(
        from start: TimeInterval,
        to end: TimeInterval
    ) async throws -> [Float]?
}

// MARK: - Windowing

/// A contiguous slice of one track's transcript segments, sized for embedding.
/// Word-length segments are too short for a stable voice embedding, so
/// neighbouring words are pooled into windows of at least `minWindowSeconds`.
public struct OnbiiSpeakerWindow: Equatable, Sendable {
    /// Indices into the track's segment array that fall in this window.
    public var segmentIndices: [Int]
    /// The span of the words themselves. This is what gets a speaker label.
    public var startSeconds: TimeInterval
    public var endSeconds: TimeInterval
    /// The span of *audio* the embedder should read, which may be wider than
    /// the words. See ``OnbiiSpeakerWindowing/windows(for:minWindowSeconds:maxGapSeconds:)``.
    public var embedStartSeconds: TimeInterval
    public var embedEndSeconds: TimeInterval

    public init(
        segmentIndices: [Int],
        startSeconds: TimeInterval,
        endSeconds: TimeInterval,
        embedStartSeconds: TimeInterval? = nil,
        embedEndSeconds: TimeInterval? = nil
    ) {
        self.segmentIndices = segmentIndices
        self.startSeconds = startSeconds
        self.endSeconds = endSeconds
        self.embedStartSeconds = embedStartSeconds ?? startSeconds
        self.embedEndSeconds = embedEndSeconds ?? endSeconds
    }
}

public enum OnbiiSpeakerWindowing {
    /// Pools time-ordered segments into embedding windows. First the track is
    /// split into runs of contiguous speech wherever a silence exceeds
    /// `maxGapSeconds` — a pause is where a speaker change is most likely. Then
    /// each run is greedily pooled into windows of at least `minWindowSeconds`,
    /// and any too-short remainder is folded into the run's previous window.
    ///
    /// A run can still be shorter than `minWindowSeconds` on its own: an
    /// isolated short word bounded by long pauses is a run of one, with nothing
    /// to fold into. Rather than hand the embedder a fragment it will refuse
    /// (0.18 s of "nu" comes back `nil`, the word keeps no speaker, and the
    /// renderer then breaks a sentence in half), such a window carries a wider
    /// **embed range**: the same words, but more audio around them.
    ///
    /// The widening stops at the neighbouring words on either side, so it only
    /// ever reaches into the silence of the pause — never into another speaker's
    /// voice, which would be a worse answer than no answer.
    public static func windows(
        for segments: [OnbiiTranscriptSegment],
        minWindowSeconds: TimeInterval,
        maxGapSeconds: TimeInterval
    ) -> [OnbiiSpeakerWindow] {
        guard !segments.isEmpty else { return [] }
        var windows = [OnbiiSpeakerWindow]()
        var runStart = 0

        func end(of index: Int) -> TimeInterval {
            segments[index].startSeconds + segments[index].durationSeconds
        }

        func flushRun(_ range: Range<Int>) {
            var pooled = [OnbiiSpeakerWindow]()
            for index in range {
                if var current = pooled.last,
                   current.endSeconds - current.startSeconds < minWindowSeconds {
                    pooled.removeLast()
                    current.segmentIndices.append(index)
                    current.endSeconds = max(current.endSeconds, end(of: index))
                    pooled.append(current)
                } else {
                    pooled.append(
                        OnbiiSpeakerWindow(
                            segmentIndices: [index],
                            startSeconds: segments[index].startSeconds,
                            endSeconds: end(of: index)
                        )
                    )
                }
            }
            if pooled.count >= 2,
               let last = pooled.last,
               last.endSeconds - last.startSeconds < minWindowSeconds {
                var previous = pooled[pooled.count - 2]
                previous.segmentIndices.append(contentsOf: last.segmentIndices)
                previous.endSeconds = max(previous.endSeconds, last.endSeconds)
                pooled[pooled.count - 2] = previous
                pooled.removeLast()
            }
            windows.append(contentsOf: pooled)
        }

        for index in 1..<segments.count where
            segments[index].startSeconds - end(of: index - 1) > maxGapSeconds {
            flushRun(runStart..<index)
            runStart = index
        }
        flushRun(runStart..<segments.count)

        return windows.map { window in
            var widened = window
            guard let first = window.segmentIndices.min(),
                  let last = window.segmentIndices.max() else {
                return window
            }
            // Only the silence between this window and its neighbouring words is
            // available. Past the ends of the track, allow a bounded amount of
            // trailing audio; the embedder clamps to what the file holds.
            let lowerBound = first > 0 ? end(of: first - 1) : 0
            let upperBound = last < segments.count - 1
                ? segments[last + 1].startSeconds
                : window.endSeconds + minWindowSeconds
            let range = embedRange(
                start: window.startSeconds,
                end: window.endSeconds,
                lowerBound: lowerBound,
                upperBound: upperBound,
                minWindowSeconds: minWindowSeconds
            )
            widened.embedStartSeconds = range.start
            widened.embedEndSeconds = range.end
            return widened
        }
    }

    /// Grows `[start, end)` towards `minWindowSeconds` without crossing the
    /// bounds, taking evenly from both sides first and then spending whatever
    /// remains on whichever side still has room. Returns the span unchanged when
    /// it is already long enough, and returns the best available span — not
    /// nothing — when the bounds cannot accommodate the full width.
    static func embedRange(
        start: TimeInterval,
        end: TimeInterval,
        lowerBound: TimeInterval,
        upperBound: TimeInterval,
        minWindowSeconds: TimeInterval
    ) -> (start: TimeInterval, end: TimeInterval) {
        var deficit = minWindowSeconds - (end - start)
        guard deficit > 0 else { return (start, end) }

        var low = start
        var high = end
        let evenly = deficit / 2
        let before = min(evenly, max(0, start - lowerBound))
        let after = min(evenly, max(0, upperBound - end))
        low -= before
        high += after
        deficit -= before + after

        if deficit > 0 {
            let extra = min(deficit, max(0, low - lowerBound))
            low -= extra
            deficit -= extra
        }
        if deficit > 0 {
            high += min(deficit, max(0, upperBound - high))
        }
        return (low, high)
    }
}

// MARK: - Clustering

public enum OnbiiSpeakerClustering {
    /// Agglomerative, average-linkage clustering on cosine distance. Repeatedly
    /// merges the two nearest clusters until the smallest remaining distance
    /// exceeds `distanceThreshold`, so the number of speakers is discovered
    /// rather than assumed. Returns a 0-based cluster index per embedding,
    /// numbered by first appearance for deterministic, reading-order labels.
    public static func cluster(
        embeddings: [[Float]],
        distanceThreshold: Float
    ) -> [Int] {
        let count = embeddings.count
        if count == 0 { return [] }
        if count == 1 { return [0] }

        let normalized = embeddings.map(normalize)
        var distance = [[Float]](
            repeating: [Float](repeating: 0, count: count),
            count: count
        )
        for i in 0..<count {
            for j in (i + 1)..<count {
                let value = cosineDistance(normalized[i], normalized[j])
                distance[i][j] = value
                distance[j][i] = value
            }
        }

        var clusters = (0..<count).map { [$0] }
        while clusters.count > 1 {
            var closest: (a: Int, b: Int, distance: Float)?
            for a in 0..<clusters.count {
                for b in (a + 1)..<clusters.count {
                    let value = averageLinkage(clusters[a], clusters[b], distance)
                    if closest == nil || value < closest!.distance {
                        closest = (a, b, value)
                    }
                }
            }
            guard let pair = closest, pair.distance <= distanceThreshold else {
                break
            }
            clusters[pair.a].append(contentsOf: clusters[pair.b])
            clusters.remove(at: pair.b)
        }

        let ordered = clusters.sorted {
            ($0.min() ?? 0) < ($1.min() ?? 0)
        }
        var labels = [Int](repeating: 0, count: count)
        for (label, cluster) in ordered.enumerated() {
            for point in cluster {
                labels[point] = label
            }
        }
        return labels
    }

    private static func averageLinkage(
        _ lhs: [Int],
        _ rhs: [Int],
        _ distance: [[Float]]
    ) -> Float {
        var total: Float = 0
        for i in lhs {
            for j in rhs {
                total += distance[i][j]
            }
        }
        return total / Float(lhs.count * rhs.count)
    }

    private static func normalize(_ vector: [Float]) -> [Float] {
        let magnitude = sqrt(vector.reduce(0) { $0 + $1 * $1 })
        guard magnitude > 0 else { return vector }
        return vector.map { $0 / magnitude }
    }

    /// Cosine distance in `[0, 2]` for L2-normalized inputs.
    private static func cosineDistance(_ lhs: [Float], _ rhs: [Float]) -> Float {
        guard lhs.count == rhs.count else { return 2 }
        var dot: Float = 0
        for index in lhs.indices {
            dot += lhs[index] * rhs[index]
        }
        return 1 - dot
    }

    /// Consolidates raw clusters into speakers. A cluster counts as a real
    /// speaker when it holds at least `max(minClusterSize, minClusterFraction ×
    /// window count)` windows; every window is then reassigned to the nearest
    /// speaker centroid. This absorbs the small, noisy fragment clusters that
    /// threshold clustering leaves behind on real conversational audio (which
    /// would otherwise surface as spurious extra speakers) without assuming how
    /// many speakers there are. The fractional floor scales with recording
    /// length: tuned on real meetings, a real speaker held ≥ ~4% of the windows
    /// while spurious fragments stayed under ~1%, so a ~2% floor separates them.
    /// Returns a 0-based speaker index per embedding, numbered by first
    /// appearance. When no cluster is large enough the input labels are
    /// returned, renumbered.
    public static func consolidate(
        embeddings: [[Float]],
        labels: [Int],
        minClusterSize: Int,
        minClusterFraction: Float = 0
    ) -> [Int] {
        let count = labels.count
        guard count > 0 else { return [] }

        let floor = max(
            minClusterSize,
            Int((minClusterFraction * Float(count)).rounded(.up))
        )
        var sizes = [Int: Int]()
        for label in labels { sizes[label, default: 0] += 1 }
        let speakerLabels = sizes.filter { $0.value >= floor }
            .keys.sorted()
        guard !speakerLabels.isEmpty else {
            return renumberByFirstAppearance(labels)
        }

        let normalized = embeddings.map(normalize)
        let centroids = speakerLabels.map { label -> [Float] in
            normalize(mean(normalized.indices
                .filter { labels[$0] == label }
                .map { normalized[$0] }))
        }

        var assigned = [Int](repeating: 0, count: count)
        for index in 0..<count {
            var bestCentroid = 0
            var bestSimilarity = -Float.greatestFiniteMagnitude
            for (centroidIndex, centroid) in centroids.enumerated() {
                let similarity = 1 - cosineDistance(normalized[index], centroid)
                if similarity > bestSimilarity {
                    bestSimilarity = similarity
                    bestCentroid = centroidIndex
                }
            }
            assigned[index] = bestCentroid
        }
        return renumberByFirstAppearance(assigned)
    }

    private static func renumberByFirstAppearance(_ labels: [Int]) -> [Int] {
        var mapping = [Int: Int]()
        var next = 0
        return labels.map { label in
            if let mapped = mapping[label] { return mapped }
            let value = next
            mapping[label] = value
            next += 1
            return value
        }
    }

    private static func mean(_ vectors: [[Float]]) -> [Float] {
        guard let first = vectors.first else { return [] }
        var sum = [Float](repeating: 0, count: first.count)
        for vector in vectors {
            for index in sum.indices { sum[index] += vector[index] }
        }
        let divisor = Float(vectors.count)
        return sum.map { $0 / divisor }
    }
}

// MARK: - Diarizer

public struct OnbiiSpeakerDiarizer: Sendable {
    /// Minimum window length fed to the embedder; voice embeddings are unstable
    /// below a couple of seconds.
    public var minWindowSeconds: TimeInterval
    /// A silence longer than this forces a window boundary.
    public var maxGapSeconds: TimeInterval
    /// Cosine-distance cutoff separating "same voice" from "different voice".
    /// 0.65 was tuned on a real two-speaker recording: on conversational audio
    /// the two speakers' window embeddings sat ~0.48 apart (far tighter than
    /// clean read speech), so 0.5 shattered each speaker into fragments while
    /// 0.75 merged them. The consolidation pass below then absorbs the residual
    /// fragments, which makes the exact threshold uncritical across ~0.58–0.70.
    public var distanceThreshold: Float
    /// Absolute minimum windows for a cluster to count as a real speaker
    /// (a floor for short recordings). Smaller, noisier fragment clusters are
    /// absorbed into the nearest speaker rather than surfacing as extra
    /// `Speaker N`s.
    public var minSpeakerWindows: Int
    /// Fractional minimum share of windows for a real speaker; scales the floor
    /// with recording length so long meetings don't accrue fragment speakers.
    /// 0.02 (2%) was tuned on real meetings — real speakers held ≥ ~4% of
    /// windows, spurious fragments < ~1%.
    public var minSpeakerFraction: Float

    public init(
        minWindowSeconds: TimeInterval = 2.5,
        maxGapSeconds: TimeInterval = 1.0,
        distanceThreshold: Float = 0.65,
        minSpeakerWindows: Int = 4,
        minSpeakerFraction: Float = 0.02
    ) {
        self.minWindowSeconds = minWindowSeconds
        self.maxGapSeconds = maxGapSeconds
        self.distanceThreshold = distanceThreshold
        self.minSpeakerWindows = minSpeakerWindows
        self.minSpeakerFraction = minSpeakerFraction
    }

    /// Diarizes one track in isolation, returning its segments with `speakerID`
    /// populated (`labelPrefix` + a 1-based number). Segments in windows the
    /// embedder cannot represent keep `speakerID == nil` and render under the
    /// track's source label. Tracks are diarized separately so voices from
    /// different capture legs (microphone vs system-audio) are never merged —
    /// the strongest prior we have that they are different people.
    public func diarize(
        track segments: [OnbiiTranscriptSegment],
        using embedder: OnbiiSpeakerEmbedder,
        labelPrefix: String = "S"
    ) async throws -> [OnbiiTranscriptSegment] {
        guard !segments.isEmpty else { return [] }
        let windows = OnbiiSpeakerWindowing.windows(
            for: segments,
            minWindowSeconds: minWindowSeconds,
            maxGapSeconds: maxGapSeconds
        )

        var embeddedWindows = [(window: OnbiiSpeakerWindow, embedding: [Float])]()
        for window in windows {
            // The embed range, not the word span: a short window borrows the
            // surrounding silence so the embedder has something to work with.
            if let embedding = try await embedder.embedding(
                from: window.embedStartSeconds,
                to: window.embedEndSeconds
            ) {
                embeddedWindows.append((window, embedding))
            }
        }
        guard !embeddedWindows.isEmpty else { return segments }

        let embeddings = embeddedWindows.map(\.embedding)
        let rawLabels = OnbiiSpeakerClustering.cluster(
            embeddings: embeddings,
            distanceThreshold: distanceThreshold
        )
        let labels = OnbiiSpeakerClustering.consolidate(
            embeddings: embeddings,
            labels: rawLabels,
            minClusterSize: minSpeakerWindows,
            minClusterFraction: minSpeakerFraction
        )

        var result = segments
        for (index, entry) in embeddedWindows.enumerated() {
            let speakerID = "\(labelPrefix)\(labels[index] + 1)"
            for segmentIndex in entry.window.segmentIndices {
                result[segmentIndex].speakerID = speakerID
            }
        }
        return result
    }
}
