import Foundation

/// Rough, on-device speaker diarization: recognizing *that* a recording contains
/// different voices and attributing turns to them, without identifying who they
/// are. Apple's on-device Speech stack provides no diarization, so this derives
/// it from the source audio: speaker-sized windows are embedded by an
/// `OnbiiSpeakerEmbedder`, the embeddings are clustered by voice similarity, and
/// each transcript word inherits the speaker label of the window it falls in.
///
/// Labels are opaque and per-object (`S1`, `S2`, …). They deliberately carry no
/// cross-object or personal meaning; mapping them to named people or reusable
/// voice signatures is a later, separately provenanced step. This is derived
/// data — it never alters the preserved source, and it can be regenerated by a
/// better model later.

// MARK: - Embedder boundary

/// Produces a fixed-length voice embedding for a time window of one audio track.
/// The Core ML implementation lives behind this boundary so the clustering and
/// assignment logic stays testable without a model, and so the embedding model
/// can be replaced.
public protocol OnbiiSpeakerEmbedder: Sendable {
    /// A voice embedding for the audio in `[start, end)` seconds, or `nil` when
    /// the window cannot be embedded (too short, silent, or unreadable). The
    /// vector need not be normalized; clustering normalizes internally.
    func embedding(
        from start: TimeInterval,
        to end: TimeInterval
    ) async throws -> [Float]?
}

// MARK: - Windowing

/// A contiguous slice of one track's transcript segments, sized for embedding.
/// Word-length segments are too short for a stable voice embedding, so
/// neighbouring words are pooled into windows of at least `minWindowSeconds`.
public struct OnbiiSpeakerWindow: Equatable, Sendable {
    /// Indices into the track's segment array that fall in this window.
    public var segmentIndices: [Int]
    public var startSeconds: TimeInterval
    public var endSeconds: TimeInterval

    public init(
        segmentIndices: [Int],
        startSeconds: TimeInterval,
        endSeconds: TimeInterval
    ) {
        self.segmentIndices = segmentIndices
        self.startSeconds = startSeconds
        self.endSeconds = endSeconds
    }
}

public enum OnbiiSpeakerWindowing {
    /// Pools time-ordered segments into embedding windows. First the track is
    /// split into runs of contiguous speech wherever a silence exceeds
    /// `maxGapSeconds` — a pause is where a speaker change is most likely. Then
    /// each run is greedily pooled into windows of at least `minWindowSeconds`,
    /// and any too-short remainder is folded into the run's previous window, so
    /// no window is orphaned too short to embed reliably.
    public static func windows(
        for segments: [OnbiiTranscriptSegment],
        minWindowSeconds: TimeInterval,
        maxGapSeconds: TimeInterval
    ) -> [OnbiiSpeakerWindow] {
        guard !segments.isEmpty else { return [] }
        var windows = [OnbiiSpeakerWindow]()
        var runStart = 0

        func end(of index: Int) -> TimeInterval {
            segments[index].startSeconds + segments[index].durationSeconds
        }

        func flushRun(_ range: Range<Int>) {
            var pooled = [OnbiiSpeakerWindow]()
            for index in range {
                if var current = pooled.last,
                   current.endSeconds - current.startSeconds < minWindowSeconds {
                    pooled.removeLast()
                    current.segmentIndices.append(index)
                    current.endSeconds = max(current.endSeconds, end(of: index))
                    pooled.append(current)
                } else {
                    pooled.append(
                        OnbiiSpeakerWindow(
                            segmentIndices: [index],
                            startSeconds: segments[index].startSeconds,
                            endSeconds: end(of: index)
                        )
                    )
                }
            }
            if pooled.count >= 2,
               let last = pooled.last,
               last.endSeconds - last.startSeconds < minWindowSeconds {
                var previous = pooled[pooled.count - 2]
                previous.segmentIndices.append(contentsOf: last.segmentIndices)
                previous.endSeconds = max(previous.endSeconds, last.endSeconds)
                pooled[pooled.count - 2] = previous
                pooled.removeLast()
            }
            windows.append(contentsOf: pooled)
        }

        for index in 1..<segments.count where
            segments[index].startSeconds - end(of: index - 1) > maxGapSeconds {
            flushRun(runStart..<index)
            runStart = index
        }
        flushRun(runStart..<segments.count)
        return windows
    }
}

// MARK: - Clustering

public enum OnbiiSpeakerClustering {
    /// Agglomerative, average-linkage clustering on cosine distance. Repeatedly
    /// merges the two nearest clusters until the smallest remaining distance
    /// exceeds `distanceThreshold`, so the number of speakers is discovered
    /// rather than assumed. Returns a 0-based cluster index per embedding,
    /// numbered by first appearance for deterministic, reading-order labels.
    public static func cluster(
        embeddings: [[Float]],
        distanceThreshold: Float
    ) -> [Int] {
        let count = embeddings.count
        if count == 0 { return [] }
        if count == 1 { return [0] }

        let normalized = embeddings.map(normalize)
        var distance = [[Float]](
            repeating: [Float](repeating: 0, count: count),
            count: count
        )
        for i in 0..<count {
            for j in (i + 1)..<count {
                let value = cosineDistance(normalized[i], normalized[j])
                distance[i][j] = value
                distance[j][i] = value
            }
        }

        var clusters = (0..<count).map { [$0] }
        while clusters.count > 1 {
            var closest: (a: Int, b: Int, distance: Float)?
            for a in 0..<clusters.count {
                for b in (a + 1)..<clusters.count {
                    let value = averageLinkage(clusters[a], clusters[b], distance)
                    if closest == nil || value < closest!.distance {
                        closest = (a, b, value)
                    }
                }
            }
            guard let pair = closest, pair.distance <= distanceThreshold else {
                break
            }
            clusters[pair.a].append(contentsOf: clusters[pair.b])
            clusters.remove(at: pair.b)
        }

        let ordered = clusters.sorted {
            ($0.min() ?? 0) < ($1.min() ?? 0)
        }
        var labels = [Int](repeating: 0, count: count)
        for (label, cluster) in ordered.enumerated() {
            for point in cluster {
                labels[point] = label
            }
        }
        return labels
    }

    private static func averageLinkage(
        _ lhs: [Int],
        _ rhs: [Int],
        _ distance: [[Float]]
    ) -> Float {
        var total: Float = 0
        for i in lhs {
            for j in rhs {
                total += distance[i][j]
            }
        }
        return total / Float(lhs.count * rhs.count)
    }

    private static func normalize(_ vector: [Float]) -> [Float] {
        let magnitude = sqrt(vector.reduce(0) { $0 + $1 * $1 })
        guard magnitude > 0 else { return vector }
        return vector.map { $0 / magnitude }
    }

    /// Cosine distance in `[0, 2]` for L2-normalized inputs.
    private static func cosineDistance(_ lhs: [Float], _ rhs: [Float]) -> Float {
        guard lhs.count == rhs.count else { return 2 }
        var dot: Float = 0
        for index in lhs.indices {
            dot += lhs[index] * rhs[index]
        }
        return 1 - dot
    }
}

// MARK: - Diarizer

public struct OnbiiSpeakerDiarizer: Sendable {
    /// Minimum window length fed to the embedder; voice embeddings are unstable
    /// below a couple of seconds.
    public var minWindowSeconds: TimeInterval
    /// A silence longer than this forces a window boundary.
    public var maxGapSeconds: TimeInterval
    /// Cosine-distance cutoff separating "same voice" from "different voice".
    /// Tuned against real, participant-labeled recordings in validation.
    public var distanceThreshold: Float

    public init(
        minWindowSeconds: TimeInterval = 2.5,
        maxGapSeconds: TimeInterval = 1.0,
        distanceThreshold: Float = 0.5
    ) {
        self.minWindowSeconds = minWindowSeconds
        self.maxGapSeconds = maxGapSeconds
        self.distanceThreshold = distanceThreshold
    }

    /// Diarizes one track in isolation, returning its segments with `speakerID`
    /// populated (`labelPrefix` + a 1-based number). Segments in windows the
    /// embedder cannot represent keep `speakerID == nil` and render under the
    /// track's source label. Tracks are diarized separately so voices from
    /// different capture legs (microphone vs system-audio) are never merged —
    /// the strongest prior we have that they are different people.
    public func diarize(
        track segments: [OnbiiTranscriptSegment],
        using embedder: OnbiiSpeakerEmbedder,
        labelPrefix: String = "S"
    ) async throws -> [OnbiiTranscriptSegment] {
        guard !segments.isEmpty else { return [] }
        let windows = OnbiiSpeakerWindowing.windows(
            for: segments,
            minWindowSeconds: minWindowSeconds,
            maxGapSeconds: maxGapSeconds
        )

        var embeddedWindows = [(window: OnbiiSpeakerWindow, embedding: [Float])]()
        for window in windows {
            if let embedding = try await embedder.embedding(
                from: window.startSeconds,
                to: window.endSeconds
            ) {
                embeddedWindows.append((window, embedding))
            }
        }
        guard !embeddedWindows.isEmpty else { return segments }

        let labels = OnbiiSpeakerClustering.cluster(
            embeddings: embeddedWindows.map(\.embedding),
            distanceThreshold: distanceThreshold
        )

        var result = segments
        for (index, entry) in embeddedWindows.enumerated() {
            let speakerID = "\(labelPrefix)\(labels[index] + 1)"
            for segmentIndex in entry.window.segmentIndices {
                result[segmentIndex].speakerID = speakerID
            }
        }
        return result
    }
}
